### ISSUE TITLE
check-model-has-description fails with macros with description

### ISSUE THREAD

**Issue by PabloPardoGarcia** [dbt-checkpoint/dbt-checkpoint#14]
**Describe the bug**
I get the following error when running the pre-commit hook `check-model-has-description`:

```bash
Check the model has description...............................................Failed
- hook id: check-model-has-description
- exit code: 1

macros/generate_schema_name.sql: does not have defined description or properties file is missing.
```

my `.pre-commit-config.yaml` file looks like:

```yaml
repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: 607cb07a1918442f5963662a9aa19da8984931e6
  hooks:
    - id: check-model-has-description
```

the macros yaml file (`macros/macros.yml`) has all the descriptions:

```yaml
version: 2

macros:
  - name: generate_schema_name
    description: >
      A macro to generate the custom schema names based on the environment:

      * In `prod`:
        - If a custom schema is provided, a model's schema name should match the custom schema, rather than being concatenated to the target schema.
        - If no custom schema is provided, a model's schema name should match the target schema.

      * In other environments (e.g. `dev` or `ci`):
        - Build all models in the target schema, as in, ignore custom schema configurations.
    arguments:
      - name: custom_schema_name
        type: string
        description: The configured value of schema in the specified node, or none if a value is not supplied
      - name: node
        type: string
        description: The node that is currently being processed by dbt
```

and the `manifest.json` has the macro's description as well:

```json
"macro.dwh.generate_schema_name": {
      "unique_id": "macro.dwh.generate_schema_name",
      "package_name": "dwh",
      "root_path": "/path/to/dbt/project/dwh",
      "path": "macros/generate_schema_name.sql",
      "original_file_path": "macros/generate_schema_name.sql",
      "name": "generate_schema_name",
      "macro_sql": "{% macro generate_schema_name(custom_schema_name, node) -%}\n    {{ generate_schema_name_for_env(custom_schema_name, node) }}\n{%- endmacro %}",
      "resource_type": "macro",
      "tags": [],
      "depends_on": {
        "macros": [
          "macro.dbt.generate_schema_name_for_env"
        ]
      },
      "description": "A macro to generate the custom schema names based on the environment:\n* In `prod`:\n  - If a custom schema is provided, a model's schema name should match the custom schema, rather than being concatenated to the target schema.\n  - If no custom schema is provided, a model's schema name should match the target schema.\n\n* In other environments (e.g. `dev` or `ci`):\n  - Build all models in the target schema, as in, ignore custom schema configurations.\n",
      "meta": {},
      "docs": {
        "show": true
      },
      "patch_path": "macros/macros.yml",
      "arguments": [
        {
          "name": "custom_schema_name",
          "type": "string",
          "description": "The configured value of schema in the specified node, or none if a value is not supplied"
        },
        {
          "name": "node",
          "type": "string",
          "description": "The node that is currently being processed by dbt"
        }
      ]
    }
```

**Version:**
pre-commit-dbt 607cb07a1918442f5963662a9aa19da8984931e6
dbt v0.19.0
python 3.8.6
