### ISSUE TITLE
check-model-has-properties-file fails on macro with a valid properties yml

### ISSUE THREAD

**Issue by andrewlee-trouva** [dbt-checkpoint/dbt-checkpoint#17]
**Describe the bug**
When running the test check-model-has-properties-file with a macro, the test fails with the following error. 

```
Check the model has properties file......................................Failed
- hook id: check-model-has-properties-file
- exit code: 1

macros/grant_select_on_schemas.sql: does not have model properties defined in any .yml file.
```

The .pre-commit-config.yaml includes the rule: 

```
repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: 607cb07a1918442f5963662a9aa19da8984931e6
  hooks:
  - id: check-model-has-properties-file
   ```

And the macro has the following .yml file (the filename is the same as the macro name and is stored within the macros folder):

```version: 2

macros:
  - name: grant_select_on_schemas
    description: "Grants privileges to groups after dbt run"
    docs:
      show: false
```

Hope we can get this fixed soon as this is a really useful test to include
