### ISSUE TITLE
Generate docs for only the staged/changed model(s)

### ISSUE THREAD

**Issue by astro30** [dbt-checkpoint/dbt-checkpoint#196]
**Describe the feature you'd like** 
Be able to generate documentation only for the staged model(s).

**Additional context** 
On big code bases, `dbt docs generate` could be extremely long (several minutes). When you have to run a particular hook, let's say [check-model-has-all-columns](https://github.com/dbt-checkpoint/dbt-checkpoint/blob/main/HOOKS.md#check-model-has-all-columns), you have to execute `dbt run` and `dbt docs generate` before (it is a prerequisite). So, we can imagine to succession of hooks:
```
- repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  rev: v1.2.0
  hooks:
    - id: dbt-run
    - id: dbt-docs-generate
    - id: check-model-has-all-columns
```

`dbt-run` will default to run only changed files. But `dbt-docs-generate` will not, that is why, I want to add this feature. This will streamline "doc-related" hooks for big codebases.
