### ISSUE TITLE
`check-model-has-contract` checkpoint always passes

### ISSUE THREAD

**Issue by rsierramartinez** [dbt-checkpoint/dbt-checkpoint#297]
**Describe the bug**
`check-model-has-contract` checkpoint always passes.

It's filtering yaml files and then trying to get sql files from that list of yaml files, resulting in it never checking any files. 

**To Reproduce**
 
1. Add the checkpoint config to the pre-commit config:

```yaml
repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.6
    hooks:
      - id: check-model-has-contract
```

2. Add a dummy yaml without contract enforced

```yaml
models:
  - name: dummy
    description: dummy model
```

3. Run pre-commit for the file

```sh
pre-commit run --files "./dummy.yml"
```

**Expected behavior**
The checkpoint should fail.

**Version:**
v2.0.6

**Additional context**
The pre-commit is configured to filter yaml files [here](https://github.com/dbt-checkpoint/dbt-checkpoint/blob/2.0.6/.pre-commit-hooks.yaml#L40-L45):

```yaml
- id: check-model-has-contract
  name: Check model has contract
  description: Check model has contract enforced = True
  entry: check-model-has-contract
  language: python
  types_or: [yaml]
````

But then the checkpoint calls the method `get_model_sqls` [here](https://github.com/dbt-checkpoint/dbt-checkpoint/blob/2.0.6/dbt_checkpoint/check_model_has_contract.py#L28), which filters out any files that are not `.sql`, which means that this checkpoint never actually checks any files and always passes.

```python
sqls = get_model_sqls(paths, manifest, include_disabled)
```
