### ISSUE TITLE
Pass custom manifest and catalog path

### ISSUE THREAD

**Issue by edbizarro** [dbt-checkpoint/dbt-checkpoint#3]
How to pass custom manifest,json and catalog.json path to hooks? My dbt project it's in a subfolder and i need to append that info because the prehook give me `Unable to load manifest file ([Errno 2] No such file or directory: 'target/manifest.json')` errors

Thanks!

**Comment by tomsej** [comment]
What hook are you using? I give you the example for e.g. 
```
repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: v0.1.0
  hooks:
  - id: check-model-has-tests-by-type
    args: ["--tests", "unique=1", "data=1", "--manifest", "<path_to_your_manifest>", "--"]
```
Same applies for `catalog.json` with parameter `--catalog`
Do not forget to add `--` as the last argument. `pre-commit` is, unfortunately, using parameter `filenames` (without `--`) for the changed files and `Argparse` has a problem with that.

Nice profile image, btw :D
