### ISSUE TITLE
Unable to load manifest file ([Errno 2] No such file or directory: 'target/manifest.json')

### ISSUE THREAD

**Issue by stumelius** [dbt-checkpoint/dbt-checkpoint#31]
**Describe the bug**
Any hook that tries to read `target/manifest.json` results in `Unable to load manifest file ([Errno 2] No such file or directory: 'target/manifest.json')` if dbt project directory (contains `target/`) != git project root.

**To Reproduce**
1. Create the following project structure
```
my_project/
├── .git/
└── dbt_project/
     ├── dbt_project.yml
     ├── target/
     ├── models/
     └── ...
```
2. Run any hook that requires the manifest

**Expected behavior**
I guess the current behavior is expected but there could be an option to specify the dbt project directory.

Workaround: `cp -r dbt_project/target target`

**Version:**
v1.0.0

**Comment by tomsej** [comment]
Hi @smomni, thanks for bug report. For every hook that needs manifest, you have an argument `--manifest`, e.g.:

```
repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: v1.0.0
  hooks:
  - id: check-model-columns-have-desc
    args: ["--manifest", "dbt_project/target/manifest.json"]
```

Does it meet your needs?
